feat(os): remove more omarchy references

diff --git a/Linux/os/helpers/update b/Linux/os/helpers/update
--- a/Linux/os/helpers/update
+++ b/Linux/os/helpers/update
@@ -2,11 +2,11 @@
 
 set -e
 
-trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://omarchy.org/discord\033[0m"; read -rp "Press Enter to close..."' ERR
+trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\033[0m"; read -rp "Press Enter to close..."' ERR
 
 if [[ $1 == "-y" ]] || update-confirm; then
   snapshot create || (($? == 127))
-  update-git
+  update-time
   update-perform
 
   # Keep the window open so the output can be reviewed before it closes.
